version: "3"

services:
  helper-bot:
    build: .
    restart: on-failure
    pull_policy: build
    env_file:
      - stack.env
    container_name: helper-bot
    depends_on:
      - "lavalink"

  lavalink:
    image: "fredboat/lavalink:master"
    container_name: lavalink
    hostname: lavalink
    restart: on-failure
    volumes:
      - /root/helper-conf/lavalink.yml:/opt/Lavalink/application.yml
